---
publisher_namespace: SumoLogic
type_path: base
accepts: []
title: 
description: 
major: 0
minor: 0
release_level: alpha
patch: 0
service_container: sumologic_base
service_handle_field: 
dedicated: false
persistent: false
immutable: false
attach_post_build: false
attach_requires_restart: false
soft_service: false
target_environment_variables: 
consumer_params: 
configurators: 
service_actionators: 
constants: 
